name: Main

on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kibot.yaml'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        # Required - kibot config file
        config: config.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: 'arduino_uno.kicad_sch'
        # optional - PCB design file
        board: 'arduino_uno.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: output
