name: Main

on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '.config/**.kibot.yaml'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:latest

    steps:
    - uses: actions/checkout@v3

    - name: Quick Start
      run: |
        kibot --quick-start
        ls -al
    - name: Retrieve results
      uses: actions/upload-artifact@v2
      with:
        name: Automatic_outputs
        path: kibot_generated.kibot.yaml

    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        # Required - kibot config file
        config: .config/print.kibot.yaml
        # optional - prefix to output defined in config
        dir: output

    - name: upload results
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: output
